# Generated by Django 3.1.5 on 2021-03-13 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_string', models.CharField(max_length=120)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
